#!/usr/bin/env python
"""Train AIRI model on prepared NIST data.

This script wraps masskit_ai's training infrastructure to train an AIRI (AI
Retention Index) model on prepared NIST data.
"""

import logging
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from tempfile import NamedTemporaryFile

import click

MASSKIT_PYTHON = "/mnt/home/magled/miniconda3/envs/masskit_ai/bin/python"

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


def create_training_config(
    train_file: str,
    valid_file: str,
    test_file: str,
    output_dir: str,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    experiment_name: str,
) -> str:
    """Create a hydra config override file for AIRI training.

    Returns the config as a YAML string.
    """
    config = f"""
# AIRI Training Configuration
# Generated by train_airi.py on {datetime.now().isoformat()}

defaults:
  - input: null
  - setup: single_gpu
  - logging: mlflow_tensorboard_local
  - ml/model: PropPredictor
  - ml/embedding: prop_embedding
  - ms: ei_ri
  - paths: standard
  - _self_

experiment_name: {experiment_name}

logging:
  MSMLFlowLogger:
    tracking_uri: {output_dir}/mlruns
  MSTensorBoardLogger:
    log_dir: {output_dir}/tb_logs

hydra:
  run:
    dir: {output_dir}/hydra_output/${{hydra.job.name}}/${{now:%Y-%m-%d_%H-%M-%S}}
  output_subdir: hydra
  searchpath:
    - pkg://masskit_ai.conf
  job:
    chdir: False

input:
  checkpoint_in: null
  train:
    spectral_library: {train_file}
    where: "[('experimental_ri', '>', 0.0),('experimental_ri', '<=', 10000.0)]"
    num: null
    log_ids: False
  valid:
    spectral_library: {valid_file}
    where: "[('experimental_ri', '>', 0.0),('experimental_ri', '<=', 10000.0)]"
    num: null
  test:
    spectral_library: {test_file}
    where: "[('experimental_ri', '>', 0.0),('experimental_ri', '<=', 10000.0)]"
    num: null

ml:
  batch_size: {batch_size}
  transfer_learning: False
  limit_train_batches: 1.0
  max_epochs: {epochs}
  shuffle: True
  bayesian_network:
    bayes: False
    sample_nbr: 3
  loss:
    loss_function: L1Loss
    sqrt_intensity: False
  metrics:
    - L1Metric
    - RMSEMetric
  valid_metrics:
    - MAEScaledMetric
    - RMSEScaledMetric
    - R2ScoreMetric
  optimizer:
    optimizer_function: Adam
    lr: {learning_rate}
  lr_scheduler:
    enable: True
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6
  output_column: experimental_ri
  precision: 32
  pin_memory: True
  gradient_clip_val: 10.0
"""
    return config


def find_masskit_ai_train():
    """Find the masskit_ai train.py script."""
    # Try common locations
    possible_paths = [
        Path.home()
        / "masskit_ai"
        / "src"
        / "masskit_ai"
        / "apps"
        / "ml"
        / "peptide"
        / "train.py",
        Path(
            "/home/magled/masskit_ai/src/masskit_ai/apps/ml/peptide/train.py"
        ),
    ]

    for path in possible_paths:
        if path.exists():
            return path

    # Try to find via package
    try:
        import masskit_ai

        masskit_ai_path = Path(masskit_ai.__file__).parent
        train_path = masskit_ai_path / "apps" / "ml" / "peptide" / "train.py"
        if train_path.exists():
            return train_path
    except ImportError:
        pass

    return None


def _print_best_metrics(output_path: Path) -> None:
    """Parse MLflow metric CSVs and print best epoch summary."""
    metrics_dir = output_path / "hydra_output"
    csv_files = (
        list(metrics_dir.rglob("metrics.csv")) if metrics_dir.exists() else []
    )
    if not csv_files:
        return
    import csv

    latest = sorted(csv_files)[-1]
    rows = list(csv.DictReader(latest.open()))
    if not rows:
        return
    metric_keys = [k for k in rows[0].keys() if k not in ("step", "epoch")]
    best_epoch = min(
        rows, key=lambda r: float(r.get("val_loss", float("inf")))
    )
    logger.info("Best epoch summary (by val_loss):")
    for k in metric_keys:
        if k in best_epoch and best_epoch[k]:
            logger.info(f"  {k}: {float(best_epoch[k]):.4f}")


@click.command()
@click.option(
    "--data-dir",
    required=True,
    type=click.Path(exists=True),
    help="Directory containing prepared AIRI parquet files",
)
@click.option(
    "--output-dir",
    default="./airi_models",
    type=click.Path(),
    help="Directory to save trained models",
)
@click.option(
    "--epochs",
    default=120,
    type=int,
    help="Number of training epochs",
)
@click.option(
    "--batch-size",
    default=50,
    type=int,
    help="Training batch size",
)
@click.option(
    "--learning-rate",
    default=2e-4,
    type=float,
    help="Learning rate",
)
@click.option(
    "--experiment-name",
    default=None,
    help="Experiment name for logging (default: auto-generated)",
)
@click.option(
    "--train-file",
    default=None,
    help="Override train parquet file (default: airi_train.parquet in data-dir)",
)
@click.option(
    "--valid-file",
    default=None,
    help="Override validation parquet file",
)
@click.option(
    "--test-file",
    default=None,
    help="Override test parquet file",
)
@click.option(
    "--masskit-ai-path",
    default=None,
    type=click.Path(exists=True),
    help="Path to masskit_ai train.py (auto-detected if not specified)",
)
@click.option(
    "--use-hydra-overrides",
    is_flag=True,
    help="Use command-line hydra overrides instead of config file",
)
def main(
    data_dir: str,
    output_dir: str,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    experiment_name: str,
    train_file: str,
    valid_file: str,
    test_file: str,
    masskit_ai_path: str,
    use_hydra_overrides: bool,
):
    """Train AIRI model on prepared NIST data.

    This script uses masskit_ai's training infrastructure to train a
    PropPredictor model for retention index prediction.
    """
    data_path = Path(data_dir).resolve()
    output_path = Path(output_dir).resolve()
    output_path.mkdir(parents=True, exist_ok=True)

    # Determine data files
    train_file = train_file or str(data_path / "airi_train.parquet")
    valid_file = valid_file or str(data_path / "airi_valid.parquet")
    test_file = test_file or str(data_path / "airi_test.parquet")

    # Check files exist
    for f, name in [
        (train_file, "train"),
        (valid_file, "valid"),
        (test_file, "test"),
    ]:
        if not Path(f).exists():
            logger.error(f"{name.capitalize()} file not found: {f}")
            logger.error(
                "Run prepare_airi_data.py first to create training data"
            )
            sys.exit(1)

    # Generate experiment name
    if not experiment_name:
        experiment_name = f"airi_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

    # Find masskit_ai train.py
    if masskit_ai_path:
        train_script = Path(masskit_ai_path)
    else:
        train_script = find_masskit_ai_train()

    if not train_script:
        logger.error("Could not find masskit_ai train.py")
        logger.error("Please specify --masskit-ai-path or install masskit_ai")
        sys.exit(1)

    logger.info("=" * 60)
    logger.info("AIRI Model Training")
    logger.info("=" * 60)
    logger.info(f"Train data: {train_file}")
    logger.info(f"Valid data: {valid_file}")
    logger.info(f"Test data: {test_file}")
    logger.info(f"Output directory: {output_dir}")
    logger.info(f"Epochs: {epochs}")
    logger.info(f"Batch size: {batch_size}")
    logger.info(f"Learning rate: {learning_rate}")
    logger.info(f"Experiment name: {experiment_name}")
    logger.info(f"masskit_ai train.py: {train_script}")

    # Build the command
    if use_hydra_overrides:
        # Use command-line overrides
        cmd = [
            MASSKIT_PYTHON,
            str(train_script),
            "--config-name",
            "config_ri",
            f"input.train.spectral_library={train_file}",
            f"input.valid.spectral_library={valid_file}",
            f"input.test.spectral_library={test_file}",
            f"ml.max_epochs={epochs}",
            f"ml.batch_size={batch_size}",
            f"ml.optimizer.lr={learning_rate}",
            f"experiment_name={experiment_name}",
            f"hydra.run.dir={output_path}/hydra_output",
        ]
    else:
        # Create config file and use --config-path
        config_content = create_training_config(
            train_file=train_file,
            valid_file=valid_file,
            test_file=test_file,
            output_dir=str(output_path),
            epochs=epochs,
            batch_size=batch_size,
            learning_rate=learning_rate,
            experiment_name=experiment_name,
        )

        # Write config to output directory
        config_path = output_path / "config_train_airi.yaml"
        config_path.write_text(config_content)
        logger.info(f"Training config saved to: {config_path}")

        cmd = [
            MASSKIT_PYTHON,
            str(train_script),
            "--config-path",
            str(output_path),
            "--config-name",
            "config_train_airi",
        ]

    logger.info("\nRunning training command:")
    logger.info(" ".join(cmd))
    logger.info("=" * 60)

    # Run training
    env = os.environ.copy()
    result = subprocess.run(cmd, env=env, cwd=str(train_script.parent))

    if result.returncode != 0:
        logger.error(f"Training failed with return code {result.returncode}")
        sys.exit(result.returncode)

    logger.info("\n" + "=" * 60)
    logger.info("Training complete!")
    logger.info(f"Models saved to: {output_path}")
    logger.info("Metrics logged (val phase):")
    logger.info("  val_L1Metric       — MAE in normalized units (÷10000)")
    logger.info("  val_RMSEMetric     — RMSE in normalized units (÷10000)")
    logger.info(
        "  val_MAEScaledMetric  — MAE in RI units (lower is better, ~20-50 = good)"
    )
    logger.info("  val_RMSEScaledMetric — RMSE in RI units")
    logger.info("  val_R2ScoreMetric    — R² (closer to 1.0 = better)")
    logger.info("Check MLflow UI or hydra_output/ for full metric history.")
    logger.info("=" * 60)
    _print_best_metrics(output_path)


if __name__ == "__main__":
    main()
