model_type: neims
metadata_path: ../../data/NIST2023_GCMS_main/metadata.tsv
spectra_path: ../../data/NIST2023_GCMS_main/spectra.hdf5
splits_path: ../../data/NIST2023_GCMS_main/splits/random_no_xeno_aas_deduplicated_no_qcxms2.tsv
fp_radius: 2
fp_length: 4096
hidden_sizes:
- 2500
- 2500
- 2500
- 2500
- 2500
- 2500
- 2500
- 2500
- 2500
- 2500
dropout: 0.4981359031638645
bidirectional: true
gate_bidirectional: false
resnet_bottleneck: 0.3016130573124354
max_mass_offset: 5
gnn_type: GAT
gnn_hidden_size: 64
gnn_num_layers: 10
gnn_num_heads: 8
gnn_dropout: 0.5
pool_type: max
use_edge_features: false
use_glu: true
ffnn_hidden_sizes: null
ffnn_dropout: 0.25
min_mz: 0.0
max_mz: 750.0
bin_width: 1.0
batch_size: 128
num_workers: 4
learning_rate: 0.008657334644519428
weight_decay: 0.0
mass_power: 0.6971495894713359
loss_type: generalized_mse
decay_scale: 950.8921456317136
min_lr_multiplier: 0.05
epochs: 100
patience: 10
wandb_project: neims
wandb_entity: null
wandb_mode: online
wandb_run_name: neims_random_noqcxms2_s2
device: cuda
seed: 2
output_dir: outputs/neims_random_noqcxms2_s2
